---
# Server configuration
timezone: UTC
hostname: josemokeni

# Security
ssh_port: 22
enable_ufw: true
allowed_ports:
  - "{{ ssh_port }}"
  - 80
  - 443

# Users
admin_user: admin
admin_groups:
  - sudo

# Git configuration
git_user_name: "{{ admin_user }}"
git_user_email: "user@example.com"
git_generate_ssh_key: true
git_ssh_key_type: ed25519
git_ssh_key_bits: 4096
git_ssh_key_comment: "{{ admin_user }}@{{ hostname }}"

# Packages to install
common_packages:
  - htop
  - vim
  - curl
  - git
  - unzip
  - fail2ban
  - net-tools
  - iotop
  - ncdu
  - tmux
  - logrotate

# Monitoring and performance tools
enable_monitoring: true
